USE master 
GO


CREATE DATABASE redmine_test 
	CONTAINMENT = NONE 
	ON PRIMARY 
( 
	 NAME = N'redmine_test', FILENAME = N'D:\SQL-Server\SQLData\redmine_test.mdf' 
	,SIZE = 214848KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB 
) 
LOG ON 
( 
	 NAME = N'redmine_test_log', FILENAME = N'D:\SQL-Server\SQLLog\redmine_test_log.ldf' 
	,SIZE = 84992KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB 
) 
WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF 


GO


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN 
	EXEC redmine_test.dbo.sp_fulltext_database @action = 'enable'
END 
GO

ALTER DATABASE redmine_test SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE redmine_test SET ANSI_NULLS OFF 
GO

ALTER DATABASE redmine_test SET ANSI_PADDING OFF 
GO

ALTER DATABASE redmine_test SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE redmine_test SET ARITHABORT OFF 
GO

ALTER DATABASE redmine_test SET AUTO_CLOSE OFF 
GO

ALTER DATABASE redmine_test SET AUTO_SHRINK OFF 
GO

ALTER DATABASE redmine_test SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE redmine_test SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE redmine_test SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE redmine_test SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE redmine_test SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE redmine_test SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE redmine_test SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE redmine_test SET  DISABLE_BROKER 
GO

ALTER DATABASE redmine_test SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE redmine_test SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE redmine_test SET TRUSTWORTHY OFF 
GO

ALTER DATABASE redmine_test SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE redmine_test SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE redmine_test SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE redmine_test SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE redmine_test SET RECOVERY FULL 
GO

ALTER DATABASE redmine_test SET  MULTI_USER 
GO

ALTER DATABASE redmine_test SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE redmine_test SET DB_CHAINING OFF 
GO

ALTER DATABASE redmine_test SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE redmine_test SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE redmine_test SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE redmine_test SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE redmine_test SET QUERY_STORE = OFF
GO

ALTER DATABASE redmine_test SET  READ_WRITE 
GO
